---
- name: Disable swap immediately
  ansible.builtin.command: swapoff -a
  changed_when: false

- name: Comment out swap entry in /etc/fstab to persist after reboot
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*\s+swap\s+.*)$'
    replace: '# \1'
